package io.komikk.registry.processor

/**
 * Pure code generator: renders a [SourceSpec] list into the
 * `GeneratedSourceRegistry` source the app compiles against.
 *
 * Kept free of KSP APIs so the output contract is unit-testable without a
 * compiler environment. The generated object lives in the app module, so it
 * may reference app-side types ([io.komikk.reader.sources.SourceRegistry]).
 */
object RegistrySourceBuilder {

    const val REGISTRY_PACKAGE = "io.komikk.registry"
    const val REGISTRY_FILE = "GeneratedSourceRegistry"

    fun build(specs: List<SourceSpec>): String {
        val metas = specs.joinToString(",\n") { spec ->
            "        SourceMeta(id = ${quote(spec.id)}, name = ${quote(spec.name)}, " +
                "lang = ${quote(spec.lang)}, version = ${spec.version}, " +
                "className = ${quote(spec.className)})"
        }

        val factories = specs.joinToString(",\n") { spec ->
            "            ${quote(spec.className)} -> { http, prefs -> ${spec.className}(http, prefs) }"
        }

        return """
            |// Generated by komikk SourceRegistryProcessor. Do not edit.
            |package $REGISTRY_PACKAGE
            |
            |import io.komikk.core.Source
            |import io.komikk.core.SourceHttpExecutor
            |import io.komikk.core.SourceMeta
            |import io.komikk.core.SourcePreferences
            |import io.komikk.reader.sources.SourceRegistry
            |
            |internal object GeneratedSourceRegistry : SourceRegistry {
            |    override val metas: List<SourceMeta> = listOf(
            |$metas
            |    )
            |
            |    override fun create(meta: SourceMeta, http: SourceHttpExecutor, prefs: SourcePreferences): Source? =
            |        when (meta.className) {
            |$factories
            |            else -> null
            |        }
            |}
            |""".trimMargin() + "\n"
    }

    private fun quote(value: String): String = "\"${value.replace("\"", "\\\"")}\""
}